apiVersion: v1
kind: Pod
metadata:
  name: management
spec:
  containers:
    - name: management
      image: ubuntu
      command:
        - /bin/bash
        - "-c"
        - |
          echo "Starting package update and installation..."
          echo "Installation complete. Pausing for 35 seconds..."

          echo "Starting to process output files..."
          echo "Node, Sysbench Time (s), Factor" > /data/benchmark.csv

          declare -A nodeTimes

          for FILE in /data/*-sysbench-output.txt; do
            echo "Processing file: $FILE"
            NODE=$(basename "$FILE" -sysbench-output.txt)
            echo "Extracted node: $NODE"
            TIME=$(grep -hoP "total time:\s+\K\d+\.\d+" "$FILE")
            echo "Extracted time: $TIME"
            nodeTimes["$NODE"]=$TIME
          done

          echo "Calculating minimum time..."
          MIN_TIME=$(printf "%s\n" "${nodeTimes[@]}" | sort -n | head -1)
          echo "Minimum time: $MIN_TIME"

          echo "Calculating factors and writing to CSV..."
          for NODE in "${!nodeTimes[@]}"; do
            TIME=${nodeTimes["$NODE"]}
            FACTOR=$(awk -v time="$TIME" -v min_time="$MIN_TIME" 'BEGIN { printf "%.3f", time / min_time }')
            echo "Writing $NODE, $TIME, $FACTOR to CSV"
            echo "$NODE, $TIME, $FACTOR" >> /data/benchmark.csv
          done

          echo "Profiling completed successfully."

          sleep infinity

      workingDir: /data
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /input
          name: input
      securityContext:
        runAsUser: 0
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: api-exp-data
    - name: input
      persistentVolumeClaim:
        claimName: api-exp-input
