apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-data
spec:
  storageClassName: standard
  volumeName: nfs-v1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-input
spec:
  storageClassName: standard
  volumeName: nfs-v2
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi    

